apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzafrontend #nome do deployment
spec:
  replicas: 3 #vai executar 3 pods
  template:
    metadata:
      labels:
        app: pizzafrontend
    spec:
      containers:
        - name: pizzafrontend
          image: macoratti/pizzafrontend:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://*:80
  selector: #que vai atuar nos pods com a label pizzafrontend
    matchLabels:
      app: pizzafrontend
